removeAccountsFromAList -> removeAccountsFromList
TootSDK/TootSDK pull request #139
Opened 2023-03-30 03:20 UTC by technicat

consistent with addAccountsToList and RemoveAccountsFromListParams

https://github.com/TootSDK/TootSDK/discussions/138

2023-04-01 02:47 UTC, davidgarywood requested changes
A tiny nit on the documentation comment (I think that was our mistake not yours, but opportunity to clean up!)

2023-04-01 02:47 UTC, davidgarywood commented on Sources/TootSDK/TootClient/TootClient+Lists.swift
>      /// Add accounts to a list
```suggestion
    /// Remove account from a list
```

2023-04-01 02:50 UTC, davidgarywood approved these changes
🙏

2023-04-01 12:58 UTC, kkostov commented
I think it can be merged, if the linter is happy 😄

2023-04-01 16:29 UTC, technicat commented
Swiftint is complaining about this line

TootClient+Account.swift:114:26: warning: Blanket Disable Command Violation: The disabled 'todo' rule should be re-enabled before the end of the file (blanket_disable_command)

2023-04-02 01:35 UTC, davidgarywood commented
I'm going to approve this, and then fix the linter with a separate PR shortly

2023-04-02 01:36 UTC, davidgarywood approved these changes

2023-04-02 01:36 UTC, merged