feat: featured_tags API
TootSDK/TootSDK pull request #171
Opened 2023-06-10 17:52 UTC by technicat

Added TootClient functions to access the Mastodon featured_tags API for featuring/unfeaturing tags, and viewing and suggesting featured tags.

https://docs.joinmastodon.org/methods/featured_tags/

Placed them in TootClient+FeaturedTags.swift and moved the existing getFeaturedTags (that takes an account ID) there.

2023-06-13 17:45 UTC, kkostov requested changes
Looks good!
I just peeked into the docs of other flavours and it seems these are all mastodon-only.

2023-06-13 17:45 UTC, kkostov commented on Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift
> +            $0.url = getURL(["api", "v1", "featured_tags", "suggestions"])
All endpoints using `featured_tags` should be limited to the mastodon flavour.

2023-06-14 03:03 UTC, technicat commented on Sources/TootSDK/TootClient/TootClient+FeaturedTags.swift
> +            $0.url = getURL(["api", "v1", "featured_tags", "suggestions"])
Done, added

```
try requireFlavour([.mastodon])
```

to each

2023-06-18 09:10 UTC, kkostov approved these changes
Nice! Thank you!

2023-06-18 09:11 UTC, davidgarywood approved these changes
Great stuff @technicat - thank you!

2023-06-18 09:11 UTC, merged